### ISSUE TITLE
how do i generate compatible csv files 

### ISSUE THREAD

**Issue by mices** [autotelik/datashift_spree#69]
Suggested use is to import csv files created by what?

**Comment by autotelik** [comment]
Hi ... there is a helper : thor datashift:generate:csv -m, --model=MODEL -r, --result=RESULT

That will generate a template file with the headers of the model. So you can generate this for Spree::Product  

Also, there is equivalent cli to generate Excel instead of CSV.

Then you can take you data from another system, and place it in the right columns for Spree

This may help (unfortunately I have not worked with Spree  for a while so may need tweaking for latest versions)

https://github.com/autotelik/datashift/wiki/Walkthroughs

**Comment by mices** [comment]
What about spree prices being a separate table?

**Comment by autotelik** [comment]
AFAIK that is for variants. to load a base product, you need to specify a price column

Spree is a complicated data model, price is actually on the Master Variant not the Product table
hence why it might not be auto generated

Also means when you run the import, you have to tell datashift to process the price method
even though it is not on the product model (its a delegated method) using --force

 t datashift:import:excel -i /tmp/product.xls -m Spree::Product --force price



my albums   : http://aqwan.bandcamp.com
free stream : http://soundcloud.com/aqwan

 

    On Thursday, 14 June 2018, 07:57:27 CEST, mices <notifications@github.com> wrote:  
 
 
What about spree prices being a separate table?

**Comment by autotelik** [comment]
AFAIK Price Table is for variants. to load a base product, you need to specify a price column

Spree is a complicated data model, price is actually on the Master Variant not the Product table
hence why it might not be auto generated

Also means when you run the import, you have to tell datashift to process the price method
even though it is not on the product model (its a delegated method) using --force

 t datashift:import:excel -i /tmp/product.xls -m Spree::Product --force price

**Comment by autotelik** [comment]
Just to confirm - to create a basic Product, you only need to set the Price field 
i.e Add a price column and run with datashift:import:excel with ```--force price```

As I mentioned the force is required because price is a method delegated from the master Variant so it does not show up in normal Rails/Ruby reflection methods

You can then setup complex variants and pricing through GUI or a custom script

> Prices are now stored in a separate table, called `spree_prices`. This table tracks the variant, the price amount, and the currency. **This allows for variants to have different prices in different currencies.**

**Comment by autotelik** [comment]
FYI - was playing around in console and this isa way to create the complex Prices

product.master.prices.create(currency: "GBP", amount: "2.0", variant: product.master)

**Comment by mices** [comment]
By what magic will currency, amount and variant insert into spree_prices ? datashift is know to do this from the model name Spree::Product (besides --force  price) ?

**Comment by mices** [comment]
t datashift:import:excel -i /tmp/product.xls -m Spree::Product --force price

What's the prepended t for?

**Comment by mices** [comment]
Do you recommend using that method, with datashift using the active record associations or generate separate templates for every model/table for simplicity and certainty's sake ?
